name: sage-2.3.0-vdw
channels:
  - conda-forge
  - openeye
  - nvidia/label/cuda-12.4.0

dependencies:
  - python
  - pip

  # OpenFF
  - openff-toolkit-base >=0.11.0
  - openff-nagl
  - openff-units !=0.2.3
  - openff-interchange-base >=0.3.18
  # - openff-qcsubmit
  # - openff-bespokefit
  # - qcportal
  # - qubekit
  # - ndcctools

  # Evaluator relevant
  - openff-evaluator ==0.5.0
  - cuda-toolkit ==12.4.0
  - openmm >=7.6,<9

  - ipykernel
  - seaborn
  - mdanalysis
  - click
  - click-option-group

  - pip:
    - git+https://github.com/openforcefield/yammbs.git
