name: Determine updated images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  get-new-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      changed_images: ${{ steps.changed_images.outputs.CHANGED_IMAGES }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ensure we only have one instance running
        uses: softprops/turnstyle@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          abort-after-seconds: 60
      
      - name: Figure out which images have changed, getting parent directory
        id: changed_images
        run: |
          git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main
          # diff between @main and current
          CHANGED_IMAGES=$(git diff --name-only origin/main ${{ github.sha }} images/ | xargs -n 1 dirname | xargs -n 1 basename | uniq | sort -u)
          echo $CHANGED_IMAGES

          # join together with quotes and commas
          CHANGED_IMAGES=$(printf "{'image': '%s'}," ${CHANGED_IMAGES[@]})
          CHANGED_IMAGES="[${CHANGED_IMAGES%}]"
          echo $CHANGED_IMAGES

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGED_IMAGES<<$EOF" >> $GITHUB_OUTPUT
          echo $CHANGED_IMAGES >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

  build-deploy-docker:
    needs: get-new-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-new-images.outputs.changed_images) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.image }}
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository }}:${{ matrix.image }}